version: '2'

networks:
  traefik:
    external:
      name: traefik_webgateway

services:
  php:
    image: francken/php
    links:
      - mysql
    volumes:
      - ./:/var/www/francken

  nginx:
    image: francken/nginx
    links:
      - php
    volumes_from:
      - php
    restart: always
    networks:
      - default
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.backend=francken-web"
      - "traefik.frontend.rule=Host:pienter.nl.localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_webgateway"

  mysql:
    image: francken/mysql
    environment:
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    restart: always
    volumes:
     - data:/var/lib/mysql

volumes:
  data:
    driver: "local"
